# Generated by Django 3.1.7 on 2021-06-10 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210610_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='Category_Name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='category_name',
        ),
    ]
